create table ADVENTURES(
    ID INTEGER AUTO_INCREMENT,
    DATE VARCHAR(250),
    COUNTRY VARCHAR(250),
    CITY VARCHAR(250),
    STATE VARCHAR(250),
    NUM_PHOTOS INTEGER,
    BLOG_COMPLETED BOOLEAN
);